package cn.teampancake.theaurorian2.common.block;

import java.util.List;
import java.util.Map;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.util.StringRepresentable;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

/** Generated by import_dungeon_decorations.ps1; shapes are cached once, never parsed during rendering/ticking. */
public enum DungeonDecorationType implements StringRepresentable {
    HANGING_CAGE("dungeon_hanging_cage", true, true, offsets(0, 0, 0, 0, -1, 0, 0, -2, 0), null),
    HANGING_CAGED_SKELETON("dungeon_hanging_caged_skeleton", true, true, offsets(0, 0, 0, 0, -1, 0, 0, -2, 0), null),
    CAGE("dungeon_cage", true, false, offsets(0, 0, 0, 0, 1, 0, 0, 2, 0), null),
    CAGED_SKELETON("dungeon_caged_skeleton", true, false, offsets(0, 0, 0, 0, 1, 0, 0, 2, 0), null),
    BROKEN_CAGE("dungeon_broken_cage", true, false, offsets(0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1), null),
    SEATED_SKELETON("dungeon_seated_skeleton", false, false, offsets(0, 0, 0, 0, 1, 0), offsets(0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0)),
    CHAINED_SKELETON("dungeon_chained_skeleton", false, false, offsets(0, 0, 0, 0, 1, 0), offsets(0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0)),
    IMPALED_SKELETON("dungeon_impaled_skeleton", false, false, offsets(0, 0, 0, 0, 1, 0), null),
    LYING_SKELETON("dungeon_lying_skeleton", false, false, offsets(0, 0, 0, 0, 0, 1), offsets(0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1)),
    OVERHANGING_SKELETON("dungeon_overhanging_skeleton", false, false, offsets(0, 0, 0, 0, -1, -1), offsets(0, 0, 0, 0, -1, -1, 1, 0, 0, 1, -1, -1)),
    SKULL("dungeon_skull", false, false, offsets(0, 0, 0), offsets(0, 0, 0, 1, 0, 0)),
    SKULL_PILE("dungeon_skull_pile", false, false, offsets(0, 0, 0), offsets(0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1)),
    BONES("dungeon_bones", false, false, offsets(0, 0, 0), null),
    RIB_CAGE("dungeon_rib_cage", false, false, offsets(0, 0, 0), null);

    public static final StringRepresentable.EnumCodec<DungeonDecorationType> CODEC = StringRepresentable.fromEnum(DungeonDecorationType::values);
    private final String id;
    private final boolean cage;
    private final boolean hanging;
    private final BlockPos[] legacyOffsets;
    private final BlockPos[] alignedOffsets;
    private final List<Map<Direction, VoxelShape>> legacyShapes;
    private final List<Map<Direction, VoxelShape>> alignedShapes;

    DungeonDecorationType(String id, boolean cage, boolean hanging, BlockPos[] legacyOffsets, BlockPos[] alignedOffsets) {
        this.id = id;
        this.cage = cage;
        this.hanging = hanging;
        this.legacyOffsets = legacyOffsets;
        this.alignedOffsets = alignedOffsets == null ? legacyOffsets : alignedOffsets;
        this.legacyShapes = DungeonDecorationShapes.get(id, false);
        this.alignedShapes = alignedOffsets == null ? legacyShapes : DungeonDecorationShapes.get(id, true);
    }

    private static BlockPos[] offsets(int... coordinates) {
        BlockPos[] result = new BlockPos[coordinates.length / 3];
        for (int i = 0; i < result.length; i++) result[i] = new BlockPos(coordinates[i*3], coordinates[i*3+1], coordinates[i*3+2]);
        return result;
    }

    @Override public String getSerializedName() { return id; }
    public boolean cage() { return cage; }
    public boolean hanging() { return hanging; }
    public boolean hasAlignment() { return alignedOffsets != legacyOffsets; }
    public int partCount() { return alignedOffsets.length; }
    public int partCount(boolean aligned) { return aligned ? alignedOffsets.length : legacyOffsets.length; }
    public BlockPos offset(int part, boolean aligned) {
        return !aligned && part < legacyOffsets.length ? legacyOffsets[part] : alignedOffsets[part];
    }
    public VoxelShape shape(int part, Direction facing, boolean aligned) {
        var shapes = aligned ? alignedShapes : legacyShapes;
        return part < shapes.size() ? shapes.get(part).get(facing) : Shapes.empty();
    }
    public int mirroredPart(int part, boolean aligned) {
        int count = partCount(aligned), maxX = 0;
        for (int i = 0; i < count; i++) maxX = Math.max(maxX, offset(i, aligned).getX());
        BlockPos cell = offset(part, aligned);
        for (int i = 0; i < count; i++) {
            BlockPos other = offset(i, aligned);
            if (other.getX() == maxX - cell.getX() && other.getY() == cell.getY() && other.getZ() == cell.getZ()) return i;
        }
        return part;
    }
}
