package cn.teampancake.theaurorian2.client.animation;

import net.minecraft.client.animation.*;

/** Generated from the approved cow Blockbench animations by scripts/export_cow_animations.py. */
public final class AurorianCowAnimations {
    private AurorianCowAnimations() {}
    public static final AnimationDefinition IDLE_BREATHE = AnimationDefinition.Builder.withLength(4.0F).looping()
        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.0F, KeyframeAnimations.degreeVec(1.2F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.SCALE,
            new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.0F, KeyframeAnimations.scaleVec(1.007F, 1.008F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, 2.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -2.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, 2.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .build();
    public static final AnimationDefinition IDLE_CHEW_LOOK = AnimationDefinition.Builder.withLength(7.0F).looping()
        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0F, KeyframeAnimations.degreeVec(-2.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.2F, KeyframeAnimations.degreeVec(-3.0F, 16.0F, -2.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.0F, KeyframeAnimations.degreeVec(-2.0F, 18.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(5.6F, KeyframeAnimations.degreeVec(1.0F, -9.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(7.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("jaw", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(5.0F, 0.0F, -0.8F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.45F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, 0.5F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.8F, KeyframeAnimations.degreeVec(4.0F, 0.0F, -0.8F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.15F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, 0.5F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.5F, KeyframeAnimations.degreeVec(5.0F, 0.0F, -0.8F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.85F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.2F, KeyframeAnimations.degreeVec(4.0F, 0.0F, -0.7F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.55F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.0F, KeyframeAnimations.degreeVec(3.0F, 0.0F, -0.5F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.4F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(7.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.0F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, -5.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(7.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .build();
    public static final AnimationDefinition IDLE_SNIFF = AnimationDefinition.Builder.withLength(6.0F).looping()
        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(8.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.8F, KeyframeAnimations.degreeVec(27.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.4F, KeyframeAnimations.degreeVec(29.0F, -7.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.0F, KeyframeAnimations.degreeVec(26.0F, 6.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.6F, KeyframeAnimations.degreeVec(29.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.6F, KeyframeAnimations.degreeVec(8.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(6.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("jaw", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.6F, KeyframeAnimations.degreeVec(2.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.2F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.6F, KeyframeAnimations.degreeVec(2.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(6.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, 4.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -4.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(6.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .build();
    public static final AnimationDefinition IDLE_TAIL_SWISH = AnimationDefinition.Builder.withLength(3.6F).looping()
        .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-4.0F, 0.0F, 10.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.85F, KeyframeAnimations.degreeVec(-12.0F, 0.0F, -30.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-7.0F, 0.0F, 23.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.6F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, -17.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.0F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.6F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.6F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-0.0F, -5.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.4F, KeyframeAnimations.degreeVec(-2.0F, -10.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.4F, KeyframeAnimations.degreeVec(-0.0F, -3.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.6F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .build();
    public static final AnimationDefinition WALK_RELAXED = AnimationDefinition.Builder.withLength(1.2F).looping()
        .addAnimation("right_leg_1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-1.34711148e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(4.04133444e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0F, KeyframeAnimations.degreeVec(-11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_leg_2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-1.34711148e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(4.04133444e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0F, KeyframeAnimations.degreeVec(-11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(-19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_leg_1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(4.04133444e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-6.7355574e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0F, KeyframeAnimations.degreeVec(11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_leg_2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(4.04133444e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.7F, KeyframeAnimations.degreeVec(-19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(-11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-6.7355574e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.0F, KeyframeAnimations.degreeVec(11.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.1F, KeyframeAnimations.degreeVec(19.0525589F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(22.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(1.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(1.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.9F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(1.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-4.0F, 0.0F, 4.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-4.0F, 0.0F, -4.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.2F, KeyframeAnimations.degreeVec(-4.0F, 0.0F, 4.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .build();
    public static final AnimationDefinition STARTLE = AnimationDefinition.Builder.withLength(0.55F)
        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.12F, KeyframeAnimations.degreeVec(-17.0F, -5.0F, 2.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.27F, KeyframeAnimations.degreeVec(-13.0F, 2.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(-8.94526382F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.12F, KeyframeAnimations.posVec(0.0F, -0.45F, 0.35F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.27F, KeyframeAnimations.posVec(0.0F, 0.35F, 0.15F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.14F, KeyframeAnimations.degreeVec(35.0F, 0.0F, -8.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(22.0F, 0.0F, 4.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(29.5867805F, 0.0F, 4.51713979F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_leg_1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.12F, KeyframeAnimations.degreeVec(-8.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(7.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_leg_1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.12F, KeyframeAnimations.degreeVec(-8.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(7.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(-4.40872848e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_leg_2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.12F, KeyframeAnimations.degreeVec(8.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(-7.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(-6.44506464F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_leg_2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.12F, KeyframeAnimations.degreeVec(8.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.28F, KeyframeAnimations.degreeVec(-7.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(6.44506464F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .build();
    public static final AnimationDefinition RUN_SCARED = AnimationDefinition.Builder.withLength(0.6F).looping()
        .addAnimation("right_leg_1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.05F, KeyframeAnimations.degreeVec(-18.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-31.1769145F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.15F, KeyframeAnimations.degreeVec(-36.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-31.1769145F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-18.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-4.40872848e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.35F, KeyframeAnimations.degreeVec(18.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(31.1769145F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.45F, KeyframeAnimations.degreeVec(36.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(31.1769145F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(18.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(8.81745695e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_leg_2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(6.44506464F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.05F, KeyframeAnimations.degreeVec(-12.1275968F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-27.4506784F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.15F, KeyframeAnimations.degreeVec(-35.4183729F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-33.895743F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-23.2907762F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-6.44506464F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.35F, KeyframeAnimations.degreeVec(12.1275968F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(27.4506784F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.45F, KeyframeAnimations.degreeVec(35.4183729F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(33.895743F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(23.2907762F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(6.44506464F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("left_leg_1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-4.40872848e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.05F, KeyframeAnimations.degreeVec(18.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(31.1769145F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.15F, KeyframeAnimations.degreeVec(36.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(31.1769145F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(18.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(8.81745695e-15F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.35F, KeyframeAnimations.degreeVec(-18.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-31.1769145F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.45F, KeyframeAnimations.degreeVec(-36.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-31.1769145F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(-18.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-1.32261854e-14F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_leg_2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-6.44506464F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.05F, KeyframeAnimations.degreeVec(12.1275968F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(27.4506784F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.15F, KeyframeAnimations.degreeVec(35.4183729F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(33.895743F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(23.2907762F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(6.44506464F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.35F, KeyframeAnimations.degreeVec(-12.1275968F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-27.4506784F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.45F, KeyframeAnimations.degreeVec(-35.4183729F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-33.895743F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(-23.2907762F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-6.44506464F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.05F, KeyframeAnimations.posVec(0.0F, 0.2F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.posVec(0.0F, 0.6F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, 0.8F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, 0.6F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.2F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.35F, KeyframeAnimations.posVec(0.0F, 0.2F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.posVec(0.0F, 0.6F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 0.8F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.6F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.posVec(0.0F, 0.2F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.05F, KeyframeAnimations.degreeVec(-1.12583302F, 0.0F, -0.325F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-1.12583302F, 0.0F, -0.562916512F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.15F, KeyframeAnimations.degreeVec(-1.59204084e-16F, 0.0F, -0.65F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(1.12583302F, 0.0F, -0.562916512F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(1.12583302F, 0.0F, -0.325F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(3.18408168e-16F, 0.0F, -7.96020419e-17F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.35F, KeyframeAnimations.degreeVec(-1.12583302F, 0.0F, 0.325F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-1.12583302F, 0.0F, 0.562916512F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.45F, KeyframeAnimations.degreeVec(-4.77612252e-16F, 0.0F, 0.65F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(1.12583302F, 0.0F, 0.562916512F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(1.12583302F, 0.0F, 0.325F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(6.36816336e-16F, 0.0F, 1.59204084e-16F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-8.94526382F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.05F, KeyframeAnimations.degreeVec(-11.1446513F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(-12.1993874F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.15F, KeyframeAnimations.degreeVec(-11.0547362F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(-8.85534875F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(-7.80061256F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(-8.94526382F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.35F, KeyframeAnimations.degreeVec(-11.1446513F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(-12.1993874F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.45F, KeyframeAnimations.degreeVec(-11.0547362F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(-8.85534875F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(-7.80061256F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-8.94526382F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("tail", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(29.5867805F, 0.0F, 4.51713979F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.05F, KeyframeAnimations.degreeVec(24.7765617F, 0.0F, 0.610615348F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.1F, KeyframeAnimations.degreeVec(21.1897812F, 0.0F, -3.45952298F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.15F, KeyframeAnimations.degreeVec(22.4132195F, 0.0F, -6.60268492F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.2F, KeyframeAnimations.degreeVec(27.2234383F, 0.0F, -7.97666277F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.25F, KeyframeAnimations.degreeVec(30.8102188F, 0.0F, -7.21330027F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3F, KeyframeAnimations.degreeVec(29.5867805F, 0.0F, -4.51713979F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.35F, KeyframeAnimations.degreeVec(24.7765617F, 0.0F, -0.610615348F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.4F, KeyframeAnimations.degreeVec(21.1897812F, 0.0F, 3.45952298F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.45F, KeyframeAnimations.degreeVec(22.4132195F, 0.0F, 6.60268492F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.5F, KeyframeAnimations.degreeVec(27.2234383F, 0.0F, 7.97666277F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.55F, KeyframeAnimations.degreeVec(30.8102188F, 0.0F, 7.21330027F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(29.5867805F, 0.0F, 4.51713979F), AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("jaw", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6F, KeyframeAnimations.degreeVec(-0.0F, 0.0F, -0.0F), AnimationChannel.Interpolations.CATMULLROM)))
        .build();
}
